"""posts table

Revision ID: c1afc9eeddfe
Revises: 1658cdadc201
Create Date: 2020-06-09 20:10:29.866876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1afc9eeddfe'
down_revision = '1658cdadc201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conflicts',
    sa.Column('session_ID', sa.String(length=32), nullable=False),
    sa.Column('Block', sa.Boolean(), nullable=True),
    sa.Column('TimeStart', sa.Time(), nullable=True),
    sa.Column('Duration', sa.Interval(), nullable=True),
    sa.Column('Mon', sa.Boolean(), nullable=True),
    sa.Column('Tue', sa.Boolean(), nullable=True),
    sa.Column('Wed', sa.Boolean(), nullable=True),
    sa.Column('Thu', sa.Boolean(), nullable=True),
    sa.Column('Fri', sa.Boolean(), nullable=True),
    sa.Column('Classroom', sa.String(length=32), nullable=True),
    sa.Column('Instructor', sa.String(length=48), nullable=True),
    sa.ForeignKeyConstraint(['session_ID'], ['course.session_ID'], ),
    sa.PrimaryKeyConstraint('session_ID')
    )
    op.create_index(op.f('ix_course_Classroom'), 'course', ['Classroom'], unique=False)
    op.create_index(op.f('ix_course_Course_code'), 'course', ['Course_code'], unique=False)
    op.create_index(op.f('ix_course_session_ID'), 'course', ['session_ID'], unique=True)
    op.drop_index('ix_course_Classroom', table_name='course')
    op.drop_index('ix_course_Course_code', table_name='course')
    op.drop_index('ix_course_session_ID', table_name='course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_course_session_ID', 'course', ['session_ID'], unique=1)
    op.create_index('ix_course_Course_code', 'course', ['Course_code'], unique=False)
    op.create_index('ix_course_Classroom', 'course', ['Classroom'], unique=False)
    op.drop_index(op.f('ix_course_session_ID'), table_name='course')
    op.drop_index(op.f('ix_course_Course_code'), table_name='course')
    op.drop_index(op.f('ix_course_Classroom'), table_name='course')
    op.drop_table('conflicts')
    # ### end Alembic commands ###
