"""courses table

Revision ID: ca03632dc433
Revises: 
Create Date: 2020-05-20 12:37:45.143976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca03632dc433'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Classroom', sa.String(length=32), nullable=True),
    sa.Column('Course_code', sa.String(length=32), nullable=True),
    sa.Column('session_ID', sa.String(length=32), nullable=True),
    sa.Column('Course_title', sa.String(length=128), nullable=True),
    sa.Column('Credits', sa.Integer(), nullable=True),
    sa.Column('Instructor', sa.String(length=128), nullable=True),
    sa.Column('Format', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_Classroom'), 'course', ['Classroom'], unique=False)
    op.create_index(op.f('ix_course_Course_code'), 'course', ['Course_code'], unique=False)
    op.create_index(op.f('ix_course_session_ID'), 'course', ['session_ID'], unique=True)
    op.create_table('instructor',
    sa.Column('TID', sa.Integer(), nullable=False),
    sa.Column('Tname', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('TID')
    )
    op.create_table('student',
    sa.Column('SID', sa.Integer(), nullable=False),
    sa.Column('Sname', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('SID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('instructor')
    op.drop_index(op.f('ix_course_session_ID'), table_name='course')
    op.drop_index(op.f('ix_course_Course_code'), table_name='course')
    op.drop_index(op.f('ix_course_Classroom'), table_name='course')
    op.drop_table('course')
    # ### end Alembic commands ###
